function env_() {
    return{
        ID_DATABASE:"12qjgOheneR-uCWnZnb0Av69r0Y4JaAlPfLyLZHlRkb8",
        ID_DATABASE_JUR:"1DeMsqMrBrZtEg1Ogert6-Xa8jNoa1TwYsMKbuY446d0",
        ID_CARPETA: "13anaINuOoKfhvRY2D-9Cyl5U3VO14lW9",
        SHEET_BASE_LIQUIDACION:"BASE-LIQUIDACION",
        SHEET_BASE_JURIDICA:"BASE-JURIDICA",
        DOCS_SOLICITUD_ACREDOR:"1Mihu1C765qGrkAEKYgBPXkjUKjKxDuEVXf4Cj8BEyPE",
        ID_CARPETA_SOLICITUD_ACREDOR:"1Hm-e0DODpjQjbcYKGfFdqmxZ6KhWDX4H",


        ID_DATABASE_EMB_LIB:"1Kx0rH9_jC80tAvXnq0f9szlN-kH7-A4IVvIzTdAvkco",
        SHEET_BASE_INICIAL_EMBLIB:"BASE-INICIAL",
        SHEET_BASE_COMPLEMENTO_EMBLIB:"BASE-COMPLEMENTO",

    }
}